version: '3.4'

services:
  webapp:
    image: web_image:latest
    ports:
      - 5002:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002;http://+:5001
    build:
      context: ../
      dockerfile: ./WebImages/Dockerfile